services:
  strops.borgun_plugin.form.type.gateway_configuration:
    class: Strops\SyliusBorgunPlugin\Form\Type\BorgunGatewayConfigurationType
    tags:
      - { name: sylius.gateway_configuration_type, type: borgun, label: strops.borgun_plugin.gateway_label }
      - { name: form.type }

  strops.borgun_plugin.gateway_factory:
    class: Payum\Core\Bridge\Symfony\Builder\GatewayFactoryBuilder
    arguments: [Strops\SyliusBorgunPlugin\BorgunGatewayFactory]
    tags:
      - { name: payum.gateway_factory_builder, factory: borgun }

  strops.borgun_plugin.bridge.open_borgun:
    class: Strops\SyliusBorgunPlugin\Bridge\OpenBorgunBridge

  strops.borgun_plugin.borgun_action:
    class: Strops\SyliusBorgunPlugin\Action\BorgunAction
    public: true
    arguments: ['@strops.borgun_plugin.bridge.open_borgun', '@payum']
    tags:
      - { name: payum.action, factory: borgun, alias: payum.action.set_borgun }

  strops.borgun_plugin.notify_action:
    class: Strops\SyliusBorgunPlugin\Action\NotifyAction
    public: true
    arguments:
      - '@strops.borgun_plugin.bridge.open_borgun'
    tags:
      - { name: payum.action, factory: borgun, alias: payum.action.notify }